import express from 'express';
import fetch from 'node-fetch';
import cors from 'cors';
import dotenv from 'dotenv';
import OpenAI from 'openai';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

app.use((req, res, next) => {
  console.log(`➡️ ${req.method} ${req.url}`);
  next();
});

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// ============ AI TUTOR ============
app.post('/api/tutor', async (req, res) => {
  try {
    const { prompt } = req.body;

    if (!prompt || typeof prompt !== 'string') {
      return res.status(400).json({ error: 'Invalid input' });
    }

    const response = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        { role: 'system', content: 'You are an expert AI tutor helping students understand academic topics clearly and simply.' },
        { role: 'user', content: prompt }
      ],
      temperature: 0.7,
    });

    console.log("✅ Tutor response:", response);

    if (!response.choices?.[0]?.message?.content) {
      return res.status(500).json({ error: 'No response from AI tutor' });
    }

    const aiMessage = response.choices[0].message.content;
    res.json({ result: aiMessage });

  } catch (err) {
    console.error('Tutor error:', err);
    res.status(500).json({ error: 'Something went wrong with the AI tutor.' });
  }
});

// ============ ESSAY MARKER ============
app.post('/api/mark', async (req, res) => {
  try {
    const { essay, board, type } = req.body;
    console.log("📥 Essay marker input:", { essay, board, type });

    if (!essay || !board || !type) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    const aoBreakdowns = {
      'edexcel-igcse': {
        'modern-prose': 'AO1 (20), AO4 (20)',
        'unseen-poetry': 'AO2 (20)',
        'anthology-poetry': 'AO2 (15), AO3 (15)',
        'modern-drama': 'AO1 (15), AO2 (15)',
        'literary-heritage': 'AO1/AO2/AO4 (10 each)'
      },
      'aqa': {
        'drama': 'AO1 (12), AO2 (12), AO3 (6), AO4 (4)',
        'prose': 'AO1 (12), AO2 (12), AO3 (6), AO4 (4)',
        'shakespeare': 'AO1, AO2, AO3, AO4',
        'nineteenth': 'AO1, AO2, AO3',
        'unseen-poetry': 'AO1 (12), AO2 (12)',
        'power-conflict': 'AO1, AO2, AO3'
      },
      'edexcel-gcse': {
        'shakespeare-extract': 'AO2 (20)',
        'shakespeare-nonextract': 'AO1 (15), AO3 (5)',
        'modern-extract': 'AO1 (16), AO3 (16), AO4 (8)',
        'nineteenth-extract': 'AO2 (20)',
        'nineteenth-nonextract': 'AO1 (20)',
        'anthology-poetry': 'AO2 (15), AO3 (5)',
        'unseen-poetry': 'AO1 (8), AO2 (12)'
      }
    };

    const ao = aoBreakdowns[board]?.[type];
    if (!ao) {
      return res.status(400).json({ error: 'Invalid exam board or type' });
    }

    const prompt = `
You are an exam marker. Use the following Assessment Objectives: ${ao}.
Please mark the essay below based on these criteria and give a brief justification for the score:

"${essay}"
`;

    const response = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        { role: 'system', content: 'You are an exam marker evaluating student essays.' },
        { role: 'user', content: prompt }
      ],
      temperature: 0.3,
    });

    console.log("✅ Essay marker response:", response);

    if (!response.choices?.[0]?.message?.content) {
      return res.status(500).json({ error: 'No response from essay marker AI' });
    }

    const feedback = response.choices[0].message.content;
    res.json({ result: feedback });

  } catch (err) {
    console.error('Marking error:', err);
    res.status(500).json({ error: 'Something went wrong with essay marking.' });
  }
});

// ============ YOUTUBE NOTES ============
app.post('/api/notes', async (req, res) => {
  try {
    const { youtubeUrl } = req.body;

    const match = youtubeUrl.match(/(?:youtu\\.be\\/|v=)([\\w-]{11})/);
    if (!match || !match[1]) {
      return res.status(400).json({ error: 'Invalid YouTube URL' });
    }

    const videoId = match[1];
    const transcriptUrl = `https://yt.lemnoslife.com/noKey/transcript?videoId=${videoId}`;
    const response = await fetch(transcriptUrl);
    const data = await response.json();

    const text = data?.transcript?.segments?.map(seg => seg.text).join(' ') || '';
    if (!text) {
      return res.status(400).json({ error: 'No transcript found' });
    }

    const completion = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        { role: 'system', content: 'Summarise the following YouTube transcript into clear revision notes for a student.' },
        { role: 'user', content: text }
      ],
      temperature: 0.5,
    });

    console.log("✅ Notes AI response:", completion);

    if (!completion.choices?.[0]?.message?.content) {
      return res.status(500).json({ error: 'No notes generated by AI' });
    }

    const notes = completion.choices[0].message.content;
    res.json({ result: notes });

  } catch (err) {
    console.error('Notes error:', err);
    res.status(500).json({ error: 'Something went wrong generating notes.' });
  }
});

app.listen(PORT, () => {
  console.log(`✅ Server listening on port ${PORT}`);
});
